---
apiVersion: v1
kind: Service
metadata:
  name: glass-db
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: glass-db